# Generated by Django 5.2.6 on 2026-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_deleted_at_user_deleted_email_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='JAZ Home Theatres', max_length=160)),
                ('tagline', models.CharField(blank=True, default='Turnkey Home Cinema · Design · Acoustics · AV · Automation', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='Hyderabad', max_length=80)),
                ('state', models.CharField(blank=True, default='Telangana', max_length=80)),
                ('email', models.EmailField(blank=True, default='srinivas@jazhometheatres.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.CharField(blank=True, default='www.jazhometheatres.com', max_length=120)),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company profile',
            },
        ),
    ]
