# Generated by Django 5.2.6 on 2026-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='features', to='catalog.version'),
        ),
        migrations.AddField(
            model_name='shaft',
            name='applicable_models',
            field=models.ManyToManyField(blank=True, related_name='shafts', to='catalog.model3'),
        ),
        migrations.AddField(
            model_name='spare',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='spares', to='catalog.version'),
        ),
    ]
