# Generated by Django 5.2.6 on 2026-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_india_districts_and_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='default_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='spare',
            name='standard_on',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
