# Generated by Django 5.2.6 on 2026-10-06 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_standard_features_and_aluminium_shaft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('configuration', models.CharField(blank=True, default='', max_length=20)),
                ('tier', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('spec', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('specification', models.TextField(blank=True, default='')),
                ('brands', models.CharField(blank=True, default='', max_length=200)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='model3',
            name='lift_type',
        ),
        migrations.RemoveField(
            model_name='powertype',
            name='lift_type',
        ),
        migrations.RemoveField(
            model_name='version',
            name='model',
        ),
        migrations.RemoveField(
            model_name='shaft',
            name='applicable_models',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='model',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_type',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='warrantyoption',
            name='version',
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory'),
        ),
        migrations.DeleteModel(
            name='AmcOption',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='LiftType',
        ),
        migrations.DeleteModel(
            name='PowerType',
        ),
        migrations.DeleteModel(
            name='Shaft',
        ),
        migrations.DeleteModel(
            name='Model3',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='SpareType',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.DeleteModel(
            name='WarrantyOption',
        ),
    ]
