# Generated by Django 5.2.6 on 2026-10-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_package_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
