# Generated by Django 5.2.6 on 2026-08-25 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('address2', models.TextField(blank=True, default='')),
                ('landmark', models.CharField(blank=True, default='', max_length=160)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(blank=True, default='India', max_length=80)),
                ('zipcode', models.CharField(blank=True, default='', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=40, unique=True)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('version', models.CharField(blank=True, default='', max_length=80)),
                ('stops', models.CharField(blank=True, default='', max_length=40)),
                ('feature', models.CharField(blank=True, default='', max_length=120)),
                ('product_info', models.JSONField(blank=True, default=dict)),
                ('sales_info', models.JSONField(blank=True, default=dict)),
                ('payment_terms', models.JSONField(blank=True, default=list)),
                ('warranty_details', models.JSONField(blank=True, default=list)),
                ('amc_details', models.JSONField(blank=True, default=list)),
                ('exclude_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('include_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('special_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shaft_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rebate', 'Rebate'), ('Inactive', 'Inactive')], default='Pending', max_length=20)),
                ('quote_file', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotes.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
