# Generated by Django 5.2.6 on 2026-10-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_backfill_legacy_quotations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='deal_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='deal_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='deal_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='deal_reason',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='quotation',
            name='deal_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Deal done'), ('LOST', 'Deal not done')], default='OPEN', max_length=8),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rebate', 'Rebate'), ('Inactive', 'Inactive'), ('Lost', 'Lost')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('ESIGN', 'E-signature'), ('ONSITE', 'Onsite')], max_length=8)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('SIGNED', 'Signed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='SENT', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_name', models.CharField(blank=True, default='', max_length=160)),
                ('signature', models.TextField(blank=True, default='')),
                ('photo', models.TextField(blank=True, default='')),
                ('consent_text', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_signatures', to='quotes.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
