# Generated by Django 5.2.6 on 2026-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_backfill_deal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='shaft_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='version',
        ),
        migrations.AddField(
            model_name='quotation',
            name='configuration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='package',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='quotation',
            name='room',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tier',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
