// Endpoint enum — mirrors the original app's De{} map (name -> path).
export const Endpoints = {
  // auth
  Login: 'auth/login',
  VerifyOtp: 'auth/verify-otp',
  ResendOtp: 'auth/resend-otp',
  ForgotPassword: 'auth/forgot-password',
  ResetPassword: 'auth/reset-password',
  Refresh: 'auth/refreshtoken',
  Logout: 'auth/logout',
  // geography
  Country: 'quote/getCountries',
  State: 'quote/getStates',
  City: 'quote/getCities',
  // home theatre catalog
  Payment_Terms: 'quote/getPaymentTerms',
  Quote_Catalog: 'quote/catalog',
  // quote lifecycle
  Create_Quote: 'quote/createquote',
  Get_QuoteList: 'quote/getListofQuotation',
  Get_QuoteDetails: 'quote/getquote',
  Download_Quote: 'quote/converthtmltopdfanduploadasync',
  Preview_Quote: 'quote/preview',
  Rebate_Quote: 'quote/editquote',
  InActive_Quote: 'quote/deletequote',
  Confirm_Quote: 'quote/getconfirmquote',
  Update_Quote: 'quote/update',
  Quote_Rules: 'quote/rules',
  Evaluate_Quote: 'quote/evaluate',
  Quote_History: 'quote/history',
  Request_Edit: 'quote/request-edit',
  Quote_Signature: 'quote/signature',
  Esign_Send: 'quote/esign/send',
  Esign_Onsite: 'quote/esign/onsite',
  Quote_Deal: 'quote/deal',
  Deal_Analysis: 'deals/analysis',
  User_Delete_Preview: 'user/delete-preview',
  User_Delete: 'user/delete',
  // approvals / notifications / team
  Approvals_List: 'approvals/list',
  Approvals_Counts: 'approvals/counts',
  Approvals_Act: 'approvals/act',
  Approvals_Reassign: 'approvals/reassign',
  Notifications_List: 'notifications/list',
  Notifications_Read: 'notifications/read',
  Team_Tree: 'team/tree',
  Me: 'user/me',
  // users / org
  Get_User_Profile: 'user/getuserprofile',
  Add_Franchize: 'user/createfranchize',
  Get_Franchize: 'user/getfranchize',
  Add_Branch: 'user/createbranch',
  Get_Branch: 'user/getofficeaddress',
  Get_Roles: 'user/getroles',
  Get_RM: 'user/getreportingmanger',
  Add_User: 'user/createuser',
  InActive_User: 'user/deleteuser',
  Add_Profile: 'user/updatepersonalinfo',
  Change_PW: 'user/updatepassword',
  Get_User_List: 'user/userlist',
  Get_Branch_List: 'user/getofficeaddresslist',
  Get_Bank_List: 'user/getbankdetails',
  Update_User_Official: 'user/edit-user',
  Get_RM_ByUserId: 'user/editreportingmanger',
  Get_Franchize_Short_Code: 'user/getempidprefix',
  // dashboard
  Dashboard_Card_Count: 'sales/modelwise-quotation-count',
  Dashboard_Overview: 'sales/overview',
  // admin panel
  Admin_Stats: 'admin-api/stats',
  Admin_Catalog_List: 'admin-api/catalog/list',
  Admin_Catalog_Update: 'admin-api/catalog/update',
  Admin_Catalog_Create: 'admin-api/catalog/create',
  Admin_Catalog_Delete: 'admin-api/catalog/delete',
  Admin_Catalog_Refs: 'admin-api/catalog/refs',
  Admin_Company: 'admin-api/company',
  Admin_Company_Update: 'admin-api/company/update',
  Admin_Quotations: 'admin-api/quotations',
  Admin_Quotation_Status: 'admin-api/quotations/status',
  Admin_Users: 'admin-api/users',
  Admin_User_Toggle: 'admin-api/users/toggle',
  Admin_User_Create: 'admin-api/users/create',
  Admin_User_Refs: 'admin-api/users/refs',
  Admin_User_Update: 'admin-api/users/update',
  Admin_Org_Tree: 'admin-api/org/tree',
  Admin_Audit: 'admin-api/audit'
};

export default Endpoints;
